-- Supabase initialization SQL for Tanara app
-- Creates minimal tables: users, preferences, presets

create table if not exists users (
  id bigint generated by default as identity primary key,
  telegram_id text unique not null,
  created_at timestamptz default now()
);

create table if not exists preferences (
  id bigint generated by default as identity primary key,
  telegram_id text not null references users(telegram_id) on delete cascade,
  symbol text,
  interval text,
  indicators jsonb,
  settings jsonb,
  updated_at timestamptz default now()
);

create table if not exists presets (
  id bigint generated by default as identity primary key,
  telegram_id text not null references users(telegram_id) on delete cascade,
  name text,
  payload jsonb,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists idx_preferences_telegram on preferences(telegram_id);
create index if not exists idx_presets_telegram on presets(telegram_id);
